import { Product, Brand } from './types';

export const HERO_SLIDES = [
  {
    id: 1,
    name: "Golden Goose",
    sub: "Superstar",
    price: 350,
    image: "images/goldengoose.png",
    bgText: "GOLDEN GOOSE"
  },
  {
    id: 2,
    name: "Air Jordan 4 Retro",
    sub: "Black Cat",
    price: 950,
    image: "images/jordan.png",
    bgText: "BLACK CAT"
  },
  {
    id: 3,
    name: "Air Force 1 '07",
    sub: "Triple White",
    price: 110,
    image: "images/airforce1.png",
    bgText: "AIR FORCE"
  },
  {
    id: 4,
    name: "New Balance 530",
    sub: "White Silver",
    price: 120,
    image: "images/newbalance530.png",
    bgText: "NEW BALANCE"
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Air Jordan 4 Retro 'Black Cat'",
    brand: "Jordan",
    price: 950,
    category: "Basketball",
    image: "images/jordan.png",
    description: "The 2020 edition of the Air Jordan 4 Retro 'Black Cat' brings back the all-black colorway of the classic silhouette, which initially released in 2006.",
    description_ka: "Air Jordan 4 Retro 'Black Cat'-ის 2020 წლის გამოცემა აბრუნებს კლასიკური სილუეტის სრულად შავ ფერთა გამას, რომელიც პირველად 2006 წელს გამოვიდა.",
    description_ru: "Выпуск 2020 года Air Jordan 4 Retro 'Black Cat' возвращает полностью черную расцветку классического силуэта, впервые выпущенного в 2006 году.",
    sizes: [40, 41, 42, 42.5, 43, 44, 45, 46],
    colors: ["Black"],
    gallery: []
  },
  {
    id: 2,
    name: "Air Force 1 '07",
    brand: "Nike",
    price: 110,
    category: "Lifestyle",
    image: "images/airforce1.png",
    description: "The Nike Air Force 1 '07 is the b-ball OG that puts a fresh spin on what you know best: crisply stitched overlays, bold colors and the perfect amount of flash.",
    description_ka: "Nike Air Force 1 '07 არის კალათბურთის OG, რომელიც ახალ სიცოცხლეს სძენს იმას, რაც ყველაზე კარგად იცით: მკვეთრად შეკერილი ზედაპირი, თამამი ფერები და იდეალური ბზინვარება.",
    description_ru: "Nike Air Force 1 '07 — это баскетбольная классика в новом исполнении: четкие накладки, смелые цвета и идеальное сияние.",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45],
    colors: ["White"],
    gallery: []
  },
  {
    id: 3,
    name: "Lv skate",
    brand: "Louis Vuitton",
    price: 115,
    category: "Lifestyle",
    image: "images/LVskate.png",
    description: "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays and original university colors.",
    description_ka: "შექმნილია პარკეტისთვის, მაგრამ გადატანილი ქუჩაში. 80-იანი წლების კალათბურთის ეს ხატება ბრუნდება იდეალურად პრიალა ზედაპირით და ორიგინალური უნივერსიტეტის ფერებით.",
    description_ru: "Созданная для паркета, но ставшая легендой улиц, икона баскетбола 80-х возвращается с идеально блестящими накладками и оригинальными университетскими цветами.",
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black", "White"],
    gallery: []
  },
  {
    id: 4,
    name: "Timberland",
    brand: "Timberland",
    price: 120,
    category: "Lifestyle",
    image: "images/timberland.png",
    description: "The New Balance 550 'White Grey' offers a clean, neutral colorway of the vintage hoops shoe originally released in 1989.",
    description_ka: "New Balance 550 'White Grey' გვთავაზობს 1989 წელს გამოსული ვინტაჟური კალათბურთის ფეხსაცმლის სუფთა, ნეიტრალურ ფერთა გამას.",
    description_ru: "New Balance 550 'White Grey' предлагает чистую, нейтральную расцветку винтажной баскетбольной обуви, впервые выпущенной в 1989 году.",
    sizes: [40, 41, 42, 43, 44, 45],
    colors: ["White", "Grey"],
    gallery: []
  },
  {
    id: 5,
    name: "New Balance 530",
    brand: "New Balance",
    price: 130,
    category: "Running",
    image: "images/newbalance530.png",
    description: "Clean lines, versatile and timeless. The people's shoe returns with the Nike Air Max 90.",
    description_ka: "სუფთა ხაზები, მრავალფეროვანი და მარადიული. ხალხის რჩეული ფეხსაცმელი ბრუნდება ახალი სტილით.",
    description_ru: "Чистые линии, универсальность и вневременной стиль. Народная обувь возвращается с Nike Air Max 90.",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
    colors: ["White", "Grey", "Black"],
    gallery: []
  },
  {
    id: 6,
    name: "air max 90",
    brand: "Nike",
    price: 100,
    category: "Lifestyle",
    image: "images/airmax90.png",
    description: "Born on the pitch, the Samba is a timeless icon of street style. This silhouette stays true to its legacy.",
    description_ka: "დაბადებული მოედანზე, Samba არის ქუჩის სტილის მარადიული ხატება. ეს სილუეტი ერთგულია თავისი მემკვიდრეობის.",
    description_ru: "Рожденная на поле, Samba стала вечной иконой уличного стиля. Этот силуэт остается верным своему наследию.",
    sizes: [38, 39, 40, 41, 42, 43],
    colors: ["White", "Black"],
    gallery: []
  },
  {
    id: 7,
    name: "Premiata'",
    brand: "Premiata",
    price: 25000,
    category: "Grail",
    image: "images/premiata.png",
    description: "The 2016 Nike Air Mag allows users to relive the future with the auto-lacing technology famously worn by Marty McFly.",
    description_ka: "2016 წლის Nike Air Mag მომხმარებლებს საშუალებას აძლევს ხელახლა იგრძნონ მომავალი ავტომატური თასმების ტექნოლოგიით, რომელიც ცნობილია მარტი მაკფლაისგან.",
    description_ru: "Nike Air Mag 2016 года позволяет снова пережить будущее с технологией автоматической шнуровки, которую носил Марти Макфлай.",
    sizes: [42, 43, 44],
    colors: ["Grey", "Blue"],
    gallery: []
  },
  {
    id: 8,
    name: "Valentino ",
    brand: "Valentino",
    price: 350,
    category: "Lifestyle",
    image: " /images/valentino.png",
    description: "The Yeezy Boost 350 V2 'Zebra' combines a white/core black Primeknit upper with red SPLY-350 branding.",
    description_ka: "Yeezy Boost 350 V2 'Zebra' აერთიანებს თეთრ/შავ Primeknit ზედაპირს წითელ SPLY-350 ბრენდირებასთან.",
    description_ru: "Yeezy Boost 350 V2 'Zebra' сочетает черно-белый верх Primeknit с красной надписью SPLY-350.",
    sizes: [40, 41, 42, 43, 44, 45],
    colors: ["White", "Black", "Red"],
    gallery: []
  },
  {
    id: 9,
    name: "Travis Scott x Air Jordan 1 Low",
    brand: "Jordan",
    price: 1200,
    category: "Lifestyle",
    image: "images/x.png",
    description: "The Travis Scott x Air Jordan 1 Low OG 'Olive' delivers a women's exclusive colorway of the chart-topping collaboration.",
    description_ka: "Travis Scott x Air Jordan 1 Low OG 'Olive' წარმოგიდგენთ პოპულარული კოლაბორაციის ექსკლუზიურ ფერთა გამას ქალებისთვის.",
    description_ru: "Travis Scott x Air Jordan 1 Low OG 'Olive' представляет эксклюзивную женскую расцветку популярной коллаборации.",
    sizes: [36, 37, 38, 39, 40],
    colors: ["Olive", "White", "Black"],
    gallery: []
  },
  {
    id: 10,
    name: "Nike Dunk Low 'Grey Fog'",
    brand: "Nike",
    price: 180,
    category: "Lifestyle",
    image: "images/panda1.png",
    description: "Subtle, clean, and essential. The Grey Fog dunk low is a versatile staple for any rotation.",
    description_ka: "ნაზი, სუფთა და აუცილებელი. Grey Fog Dunk Low არის მრავალმხრივი მოდელი ნებისმიერი კოლექციისთვის.",
    description_ru: "Тонкий, чистый и необходимый. Grey Fog Dunk Low — универсальная основа для любой коллекции.",
    sizes: [40, 41, 42, 43, 44],
    colors: ["Grey", "White"],
    gallery: []
  },
  {
    id: 11,
    name: "Jordan 1 High 'Dark Mocha'",
    brand: "Jordan",
    price: 450,
    category: "Basketball",
    image: "images/jordan1.png",
    description: "Featuring a sail leather base with black leather overlays and mocha suede construction at the heel.",
    description_ka: "წარმოდგენილია ღია კრემისფერი ტყავის ბაზით, შავი ტყავის დეტალებით და მოკა ზამშის ქუსლით.",
    description_ru: "Модель имеет основу из кожи цвета парусины с черными кожаными накладками и замшевой вставкой цвета мокко на пятке.",
    sizes: [40, 41, 42, 43, 44, 45],
    colors: ["Brown", "White", "Black"],
    gallery: []
  },
  {
    id: 47,
    name: "Golden Goose Superstar",
    brand: "Golden Goose",
    price: 350,
    category: "Lifestyle",
    image: "images/goldengoose.png",
    description: "The quintessential Golden Goose sneaker, featuring the signature star on the side and a pre-distressed vintage look.",
    description_ka: "Golden Goose-ის კლასიკური სნიკერი, გვერდზე დატანილი საფირმო ვარსკვლავით და ვინტაჟური იერსახით.",
    description_ru: "Классические кроссовки Golden Goose с фирменной звездой сбоку и винтажным эффектом потертости.",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["White", "Silver"],
    gallery: [
      "images/goldengoose.png"
    ]
  },
  {
    id: 12,
    name: "New Balance 2002R 'Protection Pack'",
    brand: "New Balance",
    price: 180,
    category: "Lifestyle",
    image: "images/2002r.png",
    description: "A deconstructed aesthetic defines this 2002R, featuring ragged suede overlays on a breathable mesh upper.",
    description_ka: "დეკონსტრუქციული ესთეტიკა განსაზღვრავს ამ 2002R მოდელს, რომელიც გამოირჩევა დახეული ზამშის დეტალებით სუნთქვად ბადის ზედაპირზე.",
    description_ru: "Деконструктивная эстетика определяет эту модель 2002R с рваными замшевыми накладками на дышащем сетчатом верхе.",
    sizes: [39, 40, 41, 42, 43],
    colors: ["Grey"],
    gallery: []
  },
  {
    id: 13,
    name: "Adidas Superstar",
    brand: "Adidas",
    price: 90,
    category: "Lifestyle",
    image: "images/superstar.png",
    description: "The shell-toe classic. Originally made for basketball courts in the '70s, celebrated by hip hop royalty in the '80s.",
    description_ka: "ნიჟარისებრი ცხვირის კლასიკა. თავდაპირველად შეიქმნა 70-იანებში კალათბურთისთვის, 80-იანებში კი ჰიპ-ჰოპ კულტურის ნაწილი გახდა.",
    description_ru: "Классика с мыском-ракушкой. Изначально созданные для баскетбольных площадок в 70-х, прославленные звездами хип-хопа в 80-х.",
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["White", "Black"],
    gallery: []
  },
  {
    id: 14,
    name: "Jordan 4 Retro 'Military Black'",
    brand: "Jordan",
    price: 400,
    category: "Basketball",
    image: "images/jordan4white.png",
    description: "This colorway borrows the color blocking of the original 'Military Blue' release from 1989.",
    description_ka: "ეს ფერთა გამა იმეორებს 1989 წლის ორიგინალური 'Military Blue' გამოცემის ფერთა ბლოკირებას.",
    description_ru: "Эта расцветка заимствует цветовую схему оригинального релиза 'Military Blue' 1989 года.",
    sizes: [40, 41, 42, 43, 44, 45, 46],
    colors: ["White", "Black", "Grey"],
    gallery: []
  },
  {
    id: 15,
    name: "Yeezy 700 'Wave Runner'",
    brand: "Adidas",
    price: 300,
    category: "Lifestyle",
    image: "images/yeezy700.png",
    description: "The shoe that started the dad shoe trend. Features a mix of suede, mesh, and leather on a chunky Boost sole.",
    description_ka: "ფეხსაცმელი, რომელმაც დაიწყო 'მამების ფეხსაცმლის' ტრენდი. აერთიანებს ზამშს, ბადეს და ტყავს მასიურ Boost ძირზე.",
    description_ru: "Обувь, начавшая тренд 'папиных кроссовок'. Сочетание замши, сетки и кожи на массивной подошве Boost.",
    sizes: [39, 40, 41, 42, 43],
    colors: ["Grey", "Black", "Green", "Orange"],
    gallery: []
  },
  {
    id: 16,
    name: "Nike Blazer Mid '77 Vintage",
    brand: "Nike",
    price: 105,
    category: "Lifestyle",
    image: "images/blazer.png",
    description: "Harnessing the old-school look of Nike basketball, the Blazer Mid '77 Vintage features a retro midsole finish.",
    description_ka: "Nike-ის ძველებური კალათბურთის სტილის შთაგონებით, Blazer Mid '77 Vintage გამოირჩევა რეტრო ძირის დიზაინით.",
    description_ru: "Воссоздавая олдскульный стиль баскетбольного Nike, Blazer Mid '77 Vintage отличается ретро-отделкой подошвы.",
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["White"],
    gallery: []
  },
  {
    id: 17,
    name: "New Balance 9060",
    brand: "New Balance",
    price: 150,
    category: "Lifestyle",
    image: "images/9060.png",
    description: "The 9060 is a new expression of the refined style and innovation-led design that have made the 99X series home to some of the most iconic models in New Balance history.",
    description_ka: "9060 არის დახვეწილი სტილისა და ინოვაციური დიზაინის ახალი გამოხატულება, რომელმაც 99X სერია New Balance-ის ისტორიაში ერთ-ერთ ყველაზე საკულტო მოდელად აქცია.",
    description_ru: "9060 — это новое выражение утонченного стиля и инновационного дизайна, сделавшего серию 99X домом для самых культовых моделей New Balance.",
    sizes: [40, 41, 42, 43, 44],
    colors: ["Grey", "White"],
    gallery: []
  },
  {
    id: 18,
    name: "Adidas Ultraboost 1.0",
    brand: "Adidas",
    price: 190,
    category: "Running",
    image: "images/ultra.png",
    description: "Experience the energy. The Ultraboost 1.0 features a Primeknit upper and full-length Boost midsole.",
    description_ka: "იგრძენი ენერგია. Ultraboost 1.0 გამოირჩევა Primeknit ზედაპირით და სრული სიგრძის Boost ძირით.",
    description_ru: "Почувствуйте энергию. Ultraboost 1.0 оснащены верхом Primeknit и полноразмерной подошвой Boost.",
    sizes: [39, 40, 41, 42, 43, 44, 45],
    colors: ["White", "Black"],
    gallery: []
  },
  {
    id: 19,
    name: "Air Jordan 3 Retro 'White Cement'",
    brand: "Jordan",
    price: 250,
    category: "Basketball",
    image: "images/cement.png",
    description: "One of the most beloved Jordans of all time, featuring the iconic elephant print overlays.",
    description_ka: "ყველა დროის ერთ-ერთი ყველაზე საყვარელი ჯორდანი, გამორჩეული საკულტო 'სპილოს პრინტის' დეტალებით.",
    description_ru: "Одни из самых любимых Jordan всех времен, с культовыми накладками с принтом слона.",
    sizes: [41, 42, 43, 44, 45],
    colors: ["White", "Grey", "Black"],
    gallery: []
  },
  {
    id: 20,
    name: "Nike Air Max 97 'Silver Bullet'",
    brand: "Nike",
    price: 180,
    category: "Running",
    image: "images/97.png",
    description: "Inspired by Japanese bullet trains, the Air Max 97 allows you to push your style full speed ahead.",
    description_ka: "იაპონური ჩქაროსნული მატარებლებით შთაგონებული Air Max 97 საშუალებას გაძლევთ სრული სისწრაფით განავითაროთ თქვენი სტილი.",
    description_ru: "Вдохновленные японскими скоростными поездами, Air Max 97 позволяют вашему стилю двигаться на полной скорости.",
    sizes: [38, 39, 40, 41, 42],
    colors: ["Silver", "White"],
    gallery: []
  },
  {
    id: 21,
    name: "Air Jordan 11 'Concord'",
    brand: "Jordan",
    price: 400,
    category: "Basketball",
    image: "images/jordan11.png",
    description: "The sneaker that defined a generation. Patent leather meets performance mesh.",
    description_ka: "სნიკერი, რომელმაც განსაზღვრა თაობა. ლაქის ტყავი ხვდება სპორტულ ბადეს.",
    description_ru: "Кроссовки, определившие поколение. Лакированная кожа встречается с функциональной сеткой.",
    sizes: [40, 41, 42, 43, 44, 45],
    colors: ["White", "Black"],
    gallery: []
  },
  {
    id: 22,
    name: "Yeezy Slide 'Onyx'",
    brand: "Adidas",
    price: 120,
    category: "Lifestyle",
    image: "images/slide.png",
    description: "The Yeezy Slide features injected EVA foam for lightweight durability, the soft top layer in the footbed offers immediate step in comfort.",
    description_ka: "Yeezy Slide დამზადებულია EVA ქაფისგან სიმსუბუქისა და გამძლეობისთვის, რბილი ზედა ფენა კი მყისიერ კომფორტს უზრუნველყოფს.",
    description_ru: "Yeezy Slide выполнены из пены EVA для легкой прочности, мягкий верхний слой стельки обеспечивает мгновенный комфорт.",
    sizes: [38, 39, 40, 41, 42, 43],
    colors: ["Black"],
    gallery: []
  },
  {
    id: 23,
    name: "Nike Zoom Vomero 5",
    brand: "Nike",
    price: 160,
    category: "Running",
    image: "images/zoomovero.png",
    description: "Carve a new lane for yourself in the Zoom Vomero 5—your go-to for complexity, depth and easy styling.",
    description_ka: "გაიკვლიე ახალი გზა Zoom Vomero 5-თან ერთად — შენი არჩევანი კომპლექსურობისთვის, სიღრმისა და მარტივი სტილისთვის.",
    description_ru: "Проложите новый путь с Zoom Vomero 5 — ваш выбор для сложности, глубины и легкого стиля.",
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Grey", "White"],
    gallery: []
  },
  {
    id: 24,
    name: "New Balance 990v6",
    brand: "New Balance",
    price: 200,
    category: "Lifestyle",
    image: "images/990.png",
    description: "The 990v6 features a streamlined take on the mesh paneling and suede overlay construction, plus FuelCell midsole cushioning.",
    description_ka: "990v6 წარმოგიდგენთ განახლებულ ხედვას ბადის პანელებსა და ზამშის კონსტრუქციაზე, დამატებული FuelCell ძირის ამორტიზაციით.",
    description_ru: "990v6 представляет собой обтекаемый взгляд на сетчатые панели и замшевые накладки, плюс амортизация FuelCell.",
    sizes: [40, 41, 42, 43, 44, 45],
    colors: ["Grey"],
    gallery: []
  },
  {
    id: 25,
    name: "Adidas Forum Low",
    brand: "Adidas",
    price: 100,
    category: "Lifestyle",
    image: "images/forum.png",
    description: "More than just a shoe, it's a statement. The Forum Low hit the scene in '84 and gained major love on the hardwood and in the music biz.",
    description_ka: "მეტი ვიდრე უბრალოდ ფეხსაცმელი - ეს განაცხადია. Forum Low 1984 წელს გამოჩნდა და დიდი სიყვარული დაიმსახურა როგორც კალათბურთში, ისე მუსიკაში.",
    description_ru: "Больше, чем просто обувь, это заявление. Forum Low появились в 84-м и завоевали любовь на паркете и в музыкальном бизнесе.",
    sizes: [39, 40, 41, 42, 43],
    colors: ["White", "Blue"],
    gallery: []
  },
  {
    id: 26,
    name: "Jordan 4 Retro 'Red Thunder'",
    brand: "Jordan",
    price: 380,
    category: "Basketball",
    image: "images/jordan4.png",
    description: "Featuring the same color blocking as the 'Thunder' colorway, but with red accents replacing the yellow.",
    description_ka: "იმანვე ფერთა ბლოკირებით, რაც 'Thunder' მოდელში, მაგრამ ყვითელი აქცენტები ჩანაცვლებულია წითლით.",
    description_ru: "С той же цветовой схемой, что и у 'Thunder', но с красными акцентами вместо желтых.",
    sizes: [40, 41, 42, 43, 44, 45],
    colors: ["Black", "Red"],
    gallery: []
  },
  {
    id: 27,
    name: "Nike Air Huarache",
    brand: "Nike",
    price: 125,
    category: "Lifestyle",
    image: "images/huarache.png",
    description: "Built to fit your foot and designed for comfort, the Nike Air Huarache brings back a street-level favorite.",
    description_ka: "შექმნილია თქვენს ფეხზე მოსარგებად და კომფორტისთვის, Nike Air Huarache აბრუნებს ქუჩის სტილის ფავორიტს.",
    description_ru: "Созданные для идеальной посадки и комфорта, Nike Air Huarache возвращают уличный фаворит.",
    sizes: [39, 40, 41, 42],
    colors: ["White"],
    gallery: []
  },
  {
    id: 28,
    name: "Yeezy 350 V2 'Bred'",
    brand: "Adidas",
    price: 380,
    category: "Lifestyle",
    image: "images/yeezy.png",
    description: "A fan favorite, featuring a black Primeknit upper with red SPLY-350 text.",
    description_ka: "ფანების რჩეული, შავი Primeknit ზედაპირჲთ და წითელი SPLY-350 წარწერით.",
    description_ru: "Фаворит фанатов с черным верхом Primeknit и красной надписью SPLY-350.",
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: ["Black", "Red"],
    gallery: []
  },
  {
    id: 29,
    name: "New Balance 1906R",
    brand: "New Balance",
    price: 155,
    category: "Running",
    image: "images/1906r.png",
    description: "Named for the year New Balance was conceived and updated with an upper inspired by running shoe designs from the 2000s.",
    description_ka: "სახელი ეწოდა New Balance-ის დაარსების წელს და განახლდა 2000-იანი წლების სირბილის ფეხსაცმლის დიზაინით შთაგონებული ზედაპირით.",
    description_ru: "Названные в честь года основания New Balance и обновленные верхом, вдохновленным беговыми кроссовками 2000-х.",
    sizes: [40, 41, 42, 43],
    colors: ["Grey", "White"],
    gallery: []
  },
  {
    id: 30,
    name: "Adidas Gazelle",
    brand: "Adidas",
    price: 100,
    category: "Lifestyle",
    image: "images/gazelle.png",
    description: "The ultimate suede classic. The Gazelle started as an athletic shoe and evolved into a streetwear staple.",
    description_ka: "ნამდვილი ზამშის კლასიკა. Gazelle დაიწყო როგორც სპორტული ფეხსაცმელი და იქცა ქუჩის სტილის განუყრელ ნაწილად.",
    description_ru: "Абсолютная классика замши. Gazelle начинались как спортивная обувь и превратились в основу уличного стиля.",
    sizes: [37, 38, 39, 40, 41, 42],
    colors: ["Black", "White"],
    gallery: []
  },
  {
    id: 31,
    name: "Nike P-6000",
    brand: "Nike",
    price: 110,
    category: "Running",
    image: "images/nikepp.png",
    description: "A mash-up of Pegasus' past, the Nike P-6000 features breathable mesh with vertical and horizontal overlays for a 2000s running look.",
    description_ka: "Pegasus-ის წარსულის შერწყმა, Nike P-6000 გამოირჩევა სუნთქვადი ბადითა და ვერტიკალური თუ ჰორიზონტალური დეტალებით 2000-იანი წლების სტილისთვის.",
    description_ru: "Смесь прошлого Pegasus, Nike P-6000 имеет дышащую сетку с вертикальными и горизонтальными накладками для бегового образа 2000-х.",
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["White", "Silver"],
    gallery: []
  },
  {
    id: 32,
    name: "Jordan 6 Retro 'Infrared'",
    brand: "Jordan",
    price: 320,
    category: "Basketball",
    image: "images/jordan6.png",
    description: "Worn by MJ during his first championship run, this colorway features a black nubuck upper with vibrant infrared accents.",
    description_ka: "MJ-ის მიერ პირველი ჩემპიონატის დროს ნატარები ეს ფერთა გამა გამოირჩევა შავი ნუბუკის ზედაპირჲთ და მკვეთრი ინფრაწითელი აქცენტებით.",
    description_ru: "Эту расцветку MJ носил во время своего первого чемпионата: черный нубуковый верх с яркими инфракрасными акцентами.",
    sizes: [41, 42, 43, 44, 45],
    colors: ["Black", "Red"],
    gallery: []
  },
  {
    id: 33,
    name: "Nike Dunk High 'Panda'",
    brand: "Nike",
    price: 125,
    category: "Lifestyle",
    image: "images/panda.png",
    description: "The classic high-top silhouette in the versatile black and white colorway.",
    description_ka: "კლასიკური მაღალყელიანი სილუეტი მრავალმხრივ შავ-თეთრ ფერთა გამაში.",
    description_ru: "Классический высокий силуэт в универсальной черно-белой расцветке.",
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black", "White"],
    gallery: []
  },
  {
    id: 34,
    name: "New Balance 530",
    brand: "New Balance",
    price: 100,
    category: "Running",
    image: "images/newbalance530.png",
    description: "A throwback to our classic running shoes, the 530 combines casual style with modern technology.",
    description_ka: "დაბრუნება ჩვენს კლასიკურ სირბილის ფეხსაცმელებთან, 530 აერთიანებს ყოველდღიურ სტილს თანამედროვე ტექნოლოგიებთან.",
    description_ru: "Возвращение к нашим классическим беговым кроссовкам, 530 сочетает повседневный стиль с современными технологиями.",
    sizes: [38, 39, 40, 41],
    colors: ["White", "Silver"],
    gallery: []
  },
  {
    id: 35,
    name: "Adidas Stan Smith",
    brand: "Adidas",
    price: 100,
    category: "Lifestyle",
    image: "images/smith.png",
    description: "Timeless appeal. Effortless style. Everyday versatility. For over 50 years and counting, Adidas Stan Smith Shoes have continued to hold their place as an icon.",
    description_ka: "მარადიული მიმზიდველობა. მსუბუქი სტილი. ყოველდღიური მრავალმხრივობა. 50 წელზე მეტია, Adidas Stan Smith ინარჩუნებს ხატის სტატუსს.",
    description_ru: "Вневременная привлекательность. Легкий стиль. Повседневная универсальность. Уже более 50 лет Adidas Stan Smith остаются иконой.",
    sizes: [38, 39, 40, 41, 42, 43, 44, 45],
    colors: ["White", "Green"],
    gallery: []
  },
  {
    id: 36,
    name: "Jordan 1 Low 'Black Toe'",
    brand: "Jordan",
    price: 140,
    category: "Lifestyle",
    image: "images/jordan1.png",
    description: "A low-top version of the classic 'Black Toe' colorway, perfect for everyday wear.",
    description_ka: "კლასიკური 'Black Toe' ფერის დაბალყელიანი ვერსია, იდეალურია ყოველდღიური ტარებისთვის.",
    description_ru: "Низкая версия классической расцветки 'Black Toe', идеально подходящая для повседневной носки.",
    sizes: [40, 41, 42, 43],
    colors: ["White", "Black", "Red"],
    gallery: []
  },
  {
    id: 37,
    name: "Nike Air Max 1 'Big Bubble'",
    brand: "Nike",
    price: 150,
    category: "Running",
    image: "images/nikeairmax1.png",
    description: "Returning in its original form with the larger Air unit window that made it famous.",
    description_ka: "ბრუნდება ორიგინალური ფორმით და უფრო დიდი Air ფანჯრით, რომელმაც ის ასე ცნობილი გახადა.",
    description_ru: "Возвращение в оригинальной форме с увеличенным окном Air unit, которое сделало их знаменитыми.",
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["White", "Red"],
    gallery: []
  },
  {
    id: 38,
    name: "New Balance 327",
    brand: "New Balance",
    price: 100,
    category: "Lifestyle",
    image: "images/newbalance327.png",
    description: "Inspired by our 70s heritage designs, the 327 features unmatched comfort and a casual aesthetic.",
    description_ka: "70-იანი წლების დიზაინით შთაგონებული 327 გამოირჩევა განუმეორებელი კომფორტითა და ყოველდღიური ესთეტიკით.",
    description_ru: "Вдохновленные наследием 70-х, 327 отличаются непревзойденным комфортом и повседневной эстетикой.",
    sizes: [38, 39, 40, 41, 42],
    colors: ["Grey", "White"],
    gallery: []
  },
  {
    id: 39,
    name: "Adidas Campus 00s",
    brand: "Adidas",
    price: 110,
    category: "Lifestyle",
    image: "images/campus.png",
    description: "These adidas shoes take the iconic Campus 80s and update them with next-gen, skate-inspired proportions.",
    description_ka: "ეს Adidas-ის ფეხსაცმელი იღებს საკულტო Campus 80s-ს და ანახლებს მას მომავალი თაობის, სკეიტბორდინგით შთაგონებული პროპორციებით.",
    description_ru: "Эти кроссовки adidas берут культовые Campus 80s и обновляют их пропорциями нового поколения, вдохновленными скейтбордингом.",
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Black", "White"],
    gallery: []
  },
  {
    id: 40,
    name: "Jordan 5 Retro 'Metallic'",
    brand: "Jordan",
    price: 280,
    category: "Basketball",
    image: "images/jordan5.png",
    description: "Classic black nubuck meets a reflective tongue and metallic silver shark teeth on the midsole.",
    description_ka: "კლასიკური შავი ნუბუკი ხვდება ამრეკლავ ენას და მეტალიკ ვერცხლისფერ 'ზვიგენის კბილებს' ძირზე.",
    description_ru: "Классический черный нубук сочетается со светоотражающим язычком и серебристыми 'акульими зубами' на подошве.",
    sizes: [41, 42, 43, 44, 45],
    colors: ["Black", "Silver"],
    gallery: []
  },
  {
    id: 41,
    name: "Nike Air Max Plus",
    brand: "Nike",
    price: 175,
    category: "Running",
    image: "images/airmaxplus.png",
    description: "Featuring the legendary Tuned Air technology, the Air Max Plus offers a super-comfortable ride.",
    description_ka: "ლეგენდარული Tuned Air ტექნოლოგიით აღჭურვილი Air Max Plus გთავაზობთ სუპერ-კომფორტულ სიარულს.",
    description_ru: "Благодаря легендарной технологии Tuned Air, Air Max Plus обеспечивают суперкомфортную ходьбу.",
    sizes: [40, 41, 42, 43, 44],
    colors: ["White", "Blue"],
    gallery: []
  },
  {
    id: 42,
    name: "Yeezy 500 'Blush'",
    brand: "Adidas",
    price: 210,
    category: "Lifestyle",
    image: "images/yeezy500.png",
    description: "The Yeezy 500 features an upper composed of cow suede, premium leather and mesh.",
    description_ka: "Yeezy 500-ის ზედაპირი შედგება ძროხის ზამშის, პრემიუმ ტყავისა და ბადისგან.",
    description_ru: "Верх Yeezy 500 состоит из замши, премиальной кожи и сетки.",
    sizes: [39, 40, 41, 42, 43],
    colors: ["Beige"],
    gallery: []
  },
  {
    id: 43,
    name: "Nike Air Monarch IV",
    brand: "Nike",
    price: 75,
    category: "Lifestyle",
    image: "images/monarch.png",
    description: "The ultimate dad shoe. Sets you up for comfortable training with durable leather on top for support.",
    description_ka: "ნამდვილი 'მამების ფეხსაცმელი'. გაწვდით კომფორტულ ვარჯიშს გამძლე ტყავის ზედაპირით მხარდაჭერისთვის.",
    description_ru: "Идеальные 'папины кроссовки'. Обеспечивают комфортную тренировку благодаря прочному кожаному верху для поддержки.",
    sizes: [40, 41, 42, 43, 44, 45, 46],
    colors: ["White"],
    gallery: []
  },
  {
    id: 44,
    name: "Jordan 13 Retro 'Playoff'",
    brand: "Jordan",
    price: 280,
    category: "Basketball",
    image: "images/jordan13.png",
    description: "Worn by MJ during the 1998 All-Star Game and playoffs, featuring a black leather upper with the signature hologram.",
    description_ka: "MJ-ის მიერ 1998 წლის ყველა ვარსკვლავის მატჩსა და პლეიოფებში ნატარები, შავი ტყავის ზედაპირით და საფირმო ჰოლოგრამით.",
    description_ru: "MJ носил их во время матча всех звезд 1998 года и плей-офф: черный кожаный верх с фирменной голограммой.",
    sizes: [41, 42, 43, 44, 45, 46],
    colors: ["Black", "White", "Red"],
    gallery: []
  }
];

export const BRANDS: Brand[] = [
  { name: "Nike", logo: "images/Logo_NIKE.svg" },
  { name: "Jordan", logo: "https://upload.wikimedia.org/wikipedia/en/3/37/Jumpman_logo.svg" },
  { name: "Adidas", logo: "images/Adidas_Logo.svg" },
  { name: "Louis Vuitton", logo: "https://upload.wikimedia.org/wikipedia/commons/7/76/Louis_Vuitton_logo_and_wordmark.svg" },
];